FROM    ubuntu:latest

RUN     apt update
RUN     DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata
RUN     apt-get install -y \
            gcc \
            g++ \
            make \
            cmake \
            git \
            curl \
            openmpi-bin \
        &&  git clone https://github.com/catchorg/Catch2.git \
        &&  cd Catch2 \
        &&  cmake -Bbuild -H. -DBUILD_TESTING=OFF \
        &&  cmake --build build/ --target install
