name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: whoan/docker-build-with-cache-action@v5
      id: docker-base-cache
      with:
        username: "${{ secrets.DOCKER_HUB_USERNAME }}"
        password: "${{ secrets.DOCKER_HUB_PASSWORD }}"
        image_name: "${{ secrets.DOCKER_HUB_IMAGE }}" 
        dockerfile: "$GITHUB_WORKSPACE/tests/ci/Dockerfile.base"

    - name: append docker base
      env:
        DOCKER_BASE: "${{ steps.docker-base-cache.outputs.FULL_IMAGE_NAME }}"
      run: |
          sed -i '1 i\FROM '"$DOCKER_BASE" $GITHUB_WORKSPACE/tests/ci/Dockerfile

    - uses: "$GITHUB_WORKSPACE/tests/ci/"
      with:
        codecov_token: "${{ secrets.CODECOV_TOKEN }}"
